.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH LIBPLAYER-TEST 1 "10/12/2009"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
libplayer-test \- a test media player utility which uses libplayer
.SH SYNOPSIS
.B libplayer-test
[\fIoptions \fR...] [\fIfiles \fR...]
.SH DESCRIPTION
This manual page documents briefly the \fBlibplayer-test\fP command.
.PP
\fBlibplayer-test\fP is a command-line media player which uses libplayer
as a backend. It is mainly used to test and exercise libplayer capabilities.
.SH OPTIONS
.TP
\fB\-h\fR \fB\-\-help\fR
this help
.TP
\fB\-p\fR \fB\-\-player\fR <player>
specify the player (mplayer|xine|vlc|gstreamer)
.TP
\fB\-a\fR \fB\-\-audio\fR
<audioout>  specify the audio output (alsa|oss|null)
.TP
\fB\-g\fR \fB\-\-video\fR
<videoout>  specify the video output (x11|sdl:x11|xv|gl|vdpau|fb|null)
.TP
\fB\-v\fR \fB\-\-verbose\fR
increase verbosity
.PP
Default values are dummy player, auto video and auto audio output.
.PP
Commands to use libplayer\-test:
.TP
#
: change playback mode (auto or single)
.TP
\&.
: change loop value and mode
.TP
,
: enable/disable shuffle on the playlist
.TP
%
: write a text on the OSD
.HP
+/\- : increase/decrease speed
.IP
]/[ : audio delay +/\- 100 ms
0/9 : increase/decrease volume
m   : set/unset mute
2/1 : 5s forward/backward
3/4 : previous/next audio track
5/6 : previous/next subtitle
7/8 : previous/next TV analog channel
{/} : previous/next radio channel
(/) : previous/next chapter
u   : toggle subtitle visibility
a   : change aspect ratio (original/16:9)
l   : load a stream in the playlist
v   : print properties and metadata of the current stream
j   : take a video snapshot of a specific time position
y   : select a radio channel
z   : select a TV channel
i   : print current time position
p   : start a new playback
o   : pause/unpause the current playback
s   : stop the current playback
b   : start the previous stream in the playlist
n   : start the next stream in the playlist
r   : remove the current stream of the playlist
t   : remove all streams of the playlist
q   : quit libplayer\-test
.PP
Commands for dvdnav:
.TP
ARROWS
: menu navigation
.IP
BACKSPACE : return to menu
ENTER     : select
.PP
Usage: libplayer\-test [options ...] [files ...]
.TP
\fB\-h\fR \fB\-\-help\fR
this help
.TP
\fB\-p\fR \fB\-\-player\fR <player>
specify the player (mplayer|xine|vlc|gstreamer)
.TP
\fB\-a\fR \fB\-\-audio\fR
<audioout>  specify the audio output (alsa|oss|null)
.TP
\fB\-g\fR \fB\-\-video\fR
<videoout>  specify the video output (x11|sdl:x11|xv|gl|vdpau|fb|null)
.TP
\fB\-v\fR \fB\-\-verbose\fR
increase verbosity
.PP
Default values are dummy player, auto video and auto audio output.
.PP
Commands to use libplayer\-test:
.TP
#
: change playback mode (auto or single)
.TP
\&.
: change loop value and mode
.TP
,
: enable/disable shuffle on the playlist
.TP
%
: write a text on the OSD
.HP
+/\- : increase/decrease speed
.IP
]/[ : audio delay +/\- 100 ms
0/9 : increase/decrease volume
m   : set/unset mute
2/1 : 5s forward/backward
3/4 : previous/next audio track
5/6 : previous/next subtitle
7/8 : previous/next TV analog channel
{/} : previous/next radio channel
(/) : previous/next chapter
u   : toggle subtitle visibility
a   : change aspect ratio (original/16:9)
l   : load a stream in the playlist
v   : print properties and metadata of the current stream
j   : take a video snapshot of a specific time position
y   : select a radio channel
z   : select a TV channel
i   : print current time position
p   : start a new playback
o   : pause/unpause the current playback
s   : stop the current playback
b   : start the previous stream in the playlist
n   : start the next stream in the playlist
r   : remove the current stream of the playlist
t   : remove all streams of the playlist
q   : quit libplayer\-test
.PP
Commands for dvdnav:
.TP
ARROWS
: menu navigation
.IP
BACKSPACE : return to menu
ENTER     : select
.SH "SEE ALSO"
.B libplayer-testvdr
(1), 
.B libplayer-regtest
(1)
.SH AUTHOR
libplayer was written by Benjamin Zores <ben@geexbox.org> and Mathieu Schroeter <mathieu.schroeter@mycable.ch>.
.PP
This manual page was written by Davide Cavalca <davide@geexbox.org>,
for the Debian project (but may be used by others).

